[tool.uv]
index-url = "https://pypi.org/simple/"

[project]
name = "flask_server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.21",
    "dotenv>=0.9.9",
    "elevenlabs>=2.13.0",
    "flask>=3.1.2",
    "flask-cors",
    "google-api-python-client>=2.179.0",
    "langchain>=0.3.27",
    "langchain-groq>=0.3.7",
    "librosa>=0.11.0",
    "moviepy>=2.2.1",
    "opencv-python>=4.12.0.88",
    "pip>=25.2",
    "psutil>=7.0.0",
    "textblob>=0.19.0",
    "whisperx>=3.4.2",
]
